import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { Providers } from './providers'
import NavigationBar from '@/components/NavigationBar'
import { Container } from '@chakra-ui/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'ZHI QIN | Front End Developer',
    description: 'Generated by create next app',
    authors: {name: 'ZHI QIN', url: ''},
    keywords: ['react', 'chakra-ui', 'nextjs'],
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <Providers>
                    <NavigationBar/>
                    <Container maxW={'4xl'}>
                        {children}
                    </Container>
                </Providers>
            </body>
        </html>
    )
}
